---
title: "R Notebook"
output: html_notebook
---


```{r}
library(R2WinBUGS)
```


#Creation dataset (as a list)

data.lips<-list(N=N,O=O,E=E,X=X/10)

### Poisson model without random effects. 

IL MODELLO ODC è DA MODIFICARE


#File with model
```{R}
laryx.Poisson<-paste(getwd(),"/laringe_poisson_model.odc",sep="")
laryx.inits<-list(
                list(alpha0=0),
                list(alpha0=-5e-01),
                list(alpha0=rnorm(1))
            )


#Define file
path.winbugs<-paste("C:\\Users\\lofer\\WinBUGS14")

mybugsdir<-"C:\\Users\\lofer\\OneDrive\\Documenti\\GitHub\\Epidemiology_2nd_Assignment\\temp"
```

```{R}
results.Poisson<-bugs(data=data,inits=laryx.inits,
                  parameters.to.save = c("RR","alpha0"),
                  model.file=laryx.Poisson,n.chains=3,n.iter=2000,n.burnin = 1000,
                  bugs.directory=path.winbugs,debug=TRUE,codaPkg=FALSE,working.directory=mybugsdir)

print(results.Poisson)
```

#### Heterogeneity model:unstructured overdispersion

laryx.heterogenity<-paste(getwd(),"/laryx-heterogeneity-model.odc",sep="")
laryx.inits.heterogenity<-list(
                          list(alpha0=0.00000E+00, alpha1=0.00000E+00,h=rnorm(56),tau.h=exp(rnorm(1))),
                          list(alpha0=-5.00000E-01, alpha1=-2.00000E+00,h=rnorm(56),tau.h=exp(rnorm(1))),
                          list(alpha0=rnorm(1),alpha1=rnorm(1),h=rnorm(56),tau.h=exp(rnorm(1))))

results.heterogenity<-bugs(data=data.lips,inits=laryx.inits.heterogenity,
                           parameters.to.save = c("alpha0","alpha1","tau.h","sigma.h"),
                           model.file=laryx.heterogenity,n.chains=3,n.iter=10000,n.burnin =0,n.thin = 1,
                           bugs.directory=path.winbugs,debug=TRUE,codaPkg=FALSE,working.directory=mybugsdir)

#After revision of the convergence

results.heterogenity<-bugs(data=data.lips,inits=laryx.inits.heterogenity,
                      parameters.to.save = c("alpha0","alpha1","tau.h","sigma.h","resid","RR"),
                      model.file=laryx.heterogenity,n.chains=3,n.iter=15000,n.burnin = 5000,n.thin = 10,
                      bugs.directory=path.winbugs,debug=TRUE,codaPkg=FALSE,working.directory=mybugsdir)


print(results.heterogenity)





# RR = E_i exp( alpha0 + alpha1*X+s[i])
# resid = exp(s[i])
# se resid>1  vuol dir che s[i]>0 => il random effect aumenta il rischio
# al contrario se resid<1 => s[i]<0 => il random effect diminuisce il rischio


############
# pag 20-21
 # in the convolutional model ho 2 random effect: 1 è per l'etergenieta e uno è per lo spatial effect

#########################'

###Spatial model:structured overdispersion

laryx.spatial<-paste(getwd(),"//laryx-spatial-model.odc",sep="")

#Computation of the spatial weights.

library(maptools)
library(spdep)

scotland<-readSplus("scotland.txt")
plot(scotland)
data.lips<-data.frame(O=O,E=E,X=X/10)
row.names(data.lips) <- sapply(slot(scotland, "polygons"), slot, "ID")
nc_scotland <- SpatialPolygonsDataFrame(scotland,data=as(data.lips, "data.frame"))
slot(nc_scotland,"data")

#Option 1
#Spatial weights for neighbours lists obtained from the map exported from WINBUGS

#Poly2nb:Construct neighbours list from polygon list based on contiguous boundaries
xxnb <- poly2nb(nc_scotland)
#nb2listw:The function supplements a neighbours list with spatial weights 
w.scotland<-nb2listw(xxnb, style="W", zero.policy=TRUE)
card(xxnb)
attributes(w.scotland)

###Be carefully with the neighbours vector
adj<-unlist(w.scotland$neighbours)
adj<-adj[adj!=0]
data.lips.spatial<-list(N=N,O=O,E=E,X=X/10,adj=adj,num=card(xxnb),sumNumNeigh=sum(card(xxnb)) )

###Option 2: From WinBUGS

# num = c(3, 2, 1, 3, 3, 0, 5, 0, 5, 4,
#               0, 2, 3, 3, 2, 6, 6, 6, 5, 3,
#               3, 2, 4, 8, 3, 3, 4, 4, 11, 6,
#               7, 3, 4, 9, 4, 2, 4, 6, 3, 4,
#               5, 5, 4, 5, 4, 6, 6, 4, 9, 2,
#               4, 4, 4, 5, 6, 5)
# adj = c(19, 9, 5, 10, 7, 12, 28, 20, 18, 19, 12, 1, 17, 16, 13, 10, 2,  29, 23, 19, 17, 1,
#   22, 16, 7, 2, 5, 3, 19, 17, 7,  35, 32, 31, 29, 25, 29, 22, 21, 17, 10, 7,  29, 19, 16, 13, 9, 7, 56, 55, 33, 28, 20, 4,  17, 13, 9, 5, 1,
#   56, 18, 4,  50, 29, 16, 16, 10, 39, 34, 29, 9, 56, 55, 48, 47, 44, 31, 30, 27,   29, 26, 15, 43, 29, 25,  56, 32, 31, 24, 45, 33, 18, 4,
#   50, 43, 34, 26, 25, 23, 21, 17, 16, 15, 9,  55, 45, 44, 42, 38, 24, 47, 46, 35, 32, 27, 24, 14, 31, 27, 14, 55, 45, 28, 18, 54, 52, 51, 43, 42, 40, 39, 29, 23,
#   46, 37, 31, 14, 41, 37, 46, 41, 36, 35, 54, 51, 49, 44, 42, 30, 40, 34, 23, 52, 49, 39, 34, 53, 49, 46, 37, 36, 51, 43, 38, 34, 30,
#   42, 34, 29, 26, 49, 48, 38, 30, 24, 55, 33, 30, 28, 53, 47, 41, 37, 35, 31, 53, 49, 48, 46, 31, 24, 49, 47, 44, 24, 54, 53, 52, 48, 47, 44, 41, 40, 38,
#   29, 21, 54, 42, 38, 34, 54, 49, 40, 34, 49, 47, 46, 41, 52, 51, 49, 38, 34, 56, 45, 33, 30, 24, 18, 55, 27, 24, 20, 18)
# sumNumNeigh = 234
# data.lips.spatial<-list(N=N,O=O,E=E,X=X/10,adj=adj,num=num,sumNumNeigh=sumNumNeigh) 


laryx.inits.spatial<-list(
  list(alpha0=0.00000E+00, alpha1=0.00000E+00,s=rnorm(56),tau.s=exp(rnorm(1))),
  list(alpha0=-5.00000E-01, alpha1=-2.00000E+00,s=rnorm(56),tau.s=exp(rnorm(1))),
  list(alpha0=rnorm(1),alpha1=rnorm(1),s=rnorm(56),tau.s=exp(rnorm(1))))

#For check de convergence
results.spatial<-bugs(data=data.lips.spatial,inits=laryx.inits.spatial,
                           parameters.to.save = c("alpha0","alpha1","tau.s","sigma.s"),
                           model.file=laryx.spatial,n.chains=3,n.iter=15000,n.burnin = 0,n.thin=1,
                           bugs.directory=path.winbugs,debug=TRUE,codaPkg=FALSE,working.directory=mybugsdir)


results.spatial<-bugs(data=data.lips.spatial,inits=laryx.inits.spatial,
                      parameters.to.save = c("RR","alpha0","alpha1","tau.s","sigma.s","resid"),
                      model.file=laryx.spatial,n.chains=3,n.iter=20000,n.burnin = 2000,n.thin=10,
                      bugs.directory=path.winbugs,debug=TRUE,codaPkg=FALSE,working.directory=mybugsdir)

#####################################################################################

#### Convolution model:

laryx.convolution<-paste(getwd(),"//laryx-convolution-model.odc",sep="")
laryx.inits.convo<-list(
  list(alpha0=0.00000E+00, alpha1=0.00000E+00,h=rnorm(56),tau.h=exp(rnorm(1)), s=rnorm(56),tau.s=exp(rnorm(1))),
  list(alpha0=-5.00000E-01, alpha1=-2.00000E+00,h=rnorm(56),tau.h=exp(rnorm(1)),s=rnorm(56),tau.s=exp(rnorm(1))),
  list(alpha0=rnorm(1),alpha1=rnorm(1),h=rnorm(56),tau.h=exp(rnorm(1)),s=rnorm(56),tau.s=exp(rnorm(1))))


#for check convergence
results.convo<-bugs(data=data.lips.spatial,inits=laryx.inits.convo,
                    parameters.to.save = c("alpha0","alpha1","tau.s","sigma.s","tau.h","sigma.h"),
                    model.file=laryx.convolution,n.chains=3,n.iter=10000,n.burnin = 0,n.thin=1,
                    bugs.directory=path.winbugs,debug=TRUE,codaPkg=FALSE,working.directory=mybugsdir)



results.convo<-bugs(data=data.lips.spatial,inits=laryx.inits.convo,
                      parameters.to.save = c("RR","alpha0","alpha1","sigma.s","sigma.h","frac.spatial","s2.marginal", "sigma2.h"),
                      model.file=laryx.convolution,n.chains=3,n.iter=20000,n.burnin = 5000,n.thin=10,
                      bugs.directory=path.winbugs,debug=TRUE,codaPkg=FALSE,working.directory=mybugsdir)


#VISTO CHE CI SONO DUE RANDOM EFFECT LA CONVERGENZA DEI PARAM è DIFFICILE, 
#CI SONO TROPPI FATTORI. FORSE NON SONO NECESSARI ENTRMABI
# PIU PARAMETRI DI QUANTI NE NECESSITI IL MODELLO => MEGLI NON USARE IL CONVOLUTIONAL
# VISTO CHE IL BAYESIAN PROCEDURE NON RIESCE A TOARE UNA DISTRIBUZIONE A CUI CONVERGERE

print(results.convo)
print(results.spatial)
print(results.heterogenity)
