---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list=ls())

data = list(

N = 144, 
            
O = c(5, 7, 0, 0, 8, 5, 1, 10, 3, 5, 
4, 7, 3, 6, 1, 5, 4, 6, 3, 3, 2, 2, 9, 8, 6, 10, 9, 15, 14, 12, 
11, 23, 12, 4, 27, 10, 10, 10, 13, 10, 7, 13, 16, 4, 9, 4, 13, 
4, 10, 12, 18, 13, 25, 5, 12, 6, 5, 2, 3, 6, 4, 4, 6, 1, 5, 9, 
7, 1, 5, 1, 4, 3, 3, 2, 3, 9, 5, 9, 19, 4, 12, 1, 2, 8, 6, 4, 
2, 4, 8, 4, 6, 7, 4, 10, 4, 7, 8, 12, 12, 8, 6, 2, 7, 7, 7, 4, 
10, 8, 3, 5, 6, 9, 3, 10, 9, 8, 9, 6, 3, 1, 0, 1, 1, 3, 1, 0, 
1, 0, 2, 5, 0, 0, 1, 0, 0, 1, 2, 4, 2, 2, 3, 0, 0, 1), 

E = c(2.53, 3.94, 3.09, 2.75, 3.81, 3.66, 4.05, 3.07, 3.42, 4.24, 3.9, 3.58, 
3.68, 3.19, 5.15, 3.75, 3.37, 4.52, 1.94, 3.47, 3.48, 3.32, 4.52, 
9.2, 10.37, 8.08, 6.66, 7.7, 9.79, 9.77, 10.17, 9.93, 9.53, 10.59, 
7.64, 7.03, 4.09, 7.66, 8.02, 6.78, 9.85, 7.98, 8.14, 4.07, 7.54, 
7.04, 7.99, 8.1, 5.69, 6.37, 8.2, 6.52, 4.68, 9.11, 11.28, 6.18, 
4.79, 4.98, 6.47, 5.43, 6.51, 4.44, 6.69, 5.55, 6.24, 5.27, 5.61, 
5.31, 6.92, 5.17, 5.13, 3.73, 6.18, 9.44, 7.3, 7.63, 11.66, 6.52, 
6.64, 10.64, 7.15, 8.76, 7.48, 6.06, 6.36, 7.98, 8.92, 9.07, 
6.2, 7.37, 6.68, 8.62, 8.05, 5.97, 8.65, 7.04, 8.91, 5.95, 7.5, 
9.11, 10.59, 7.64, 8.91, 8.72, 11.7, 10.69, 7.73, 8.52, 7.81, 
9.24, 8.25, 10.72, 10.33, 8.19, 10.9, 7, 9.98, 10.1, 2.33, 3.49, 
0.78, 3.59, 2.47, 4.1, 1.82, 0.71, 1.44, 1.76, 3.39, 2.19, 1.66, 
1.35, 2.27, 2.11, 1.05, 2.22, 3.24, 2.65, 3.15, 1.94, 3.13, 1.95, 
2.16, 1.76))

data$SMR = data$O/data$E
```

```{r}
library(spdep)
library(sf)

shp.file <- read_sf(dsn = ".", layer = "NWEngland")
spatial.file <- sf::as_Spatial(shp.file)
spatial.file$geometry <- NULL #Eliminate this geographic information
```

```{r}
df <- as.data.frame(spatial.file) #Create a data.frame
NW.dataset <- sp::SpatialPolygonsDataFrame(spatial.file, data = df )
```

```{r}
hist(data$SMR, xlab="Standardized Mortality Rate (SMR)", main="")
```

```{r}
NW.dataset$SMR<-data$SMR
NW.dataset$NAME = NW.dataset$poly_id

plot(NW.dataset, border="blue", axes=TRUE, las=1)
text(coordinates(NW.dataset),label=NW.dataset$NAME,cex=0.4)
```

```{r}
brks <- round(quantile(NW.dataset$SMR, probs=seq(0,1,0.2)), digits=2)
my.colours <- c("yellow", "orange2", "red3", "brown", "black")
```

```{r}
library(classInt)
```

```{r}
library(maptools)
plot(NW.dataset, col=my.colours[findInterval(NW.dataset$SMR, brks,all.inside=TRUE)])
legend(x=c(-84, -80), y=c(33, 34.5), legend=leglabs(brks),fill=my.colours, bty="n",cex=0.5)
title(main=paste("Standardized Mortality Rate (SMR) during 1982-1991"))
text(coordinates(NW.dataset),label=as.factor(NW.dataset$NAME),cex=0.4)
```

```{r}
my.colours<-gray.colors(5,0.95,0.2)
plot(NW.dataset, col=my.colours[findInterval(NW.dataset$SMR, brks,all.inside=TRUE)])
legend(x=c(-84, -80), y=c(33, 34.5), legend=leglabs(brks),fill=my.colours, bty="n",cex=0.5)
title(main=paste("Standardized Mortality Rate (SMR) during 1982-1991"))
text(coordinates(NW.dataset),label=as.factor(NW.dataset$NAME),cex=0.5)
```


```{r}

#A terrain color palette.
my.colours<- terrain.colors(5)
plot(NW.dataset, col=my.colours[findInterval(NW.dataset$SMR, brks,all.inside=TRUE)])
legend(x=c(-84, -80), y=c(33, 34.5), legend=leglabs(brks),fill=my.colours, bty="n",cex=0.5)
title(main=paste("Standardized Mortality Rate (SMR) during 1982-1991"))
text(coordinates(NW.dataset),label=as.factor(NW.dataset$NAME),cex=0.4)
```


```{r}
my.colours<- rev(terrain.colors(5))
plot(NW.dataset, col=my.colours[findInterval(NW.dataset$SMR, brks,all.inside=TRUE)])
legend(x=c(-84, -80), y=c(33, 34.5), legend=leglabs(brks),fill=my.colours, bty="n",cex=0.5)
title(main=paste("Standardized Mortality Rate (SMR) during 1982-1991"))
text(coordinates(NW.dataset),label=as.factor(NW.dataset$NAME),cex=0.4)
```

## 2. Finding Spatial Neighbours

look at the borders

```{r}
xxnb <- poly2nb(NW.dataset)
plot(NW.dataset, border="grey")
plot(xxnb, coordinates(NW.dataset), add=TRUE, col="blue")
```

```{r}
summary.nb(xxnb)
```

```{r}
cards <- card(xxnb) #Cardinalities of neighbours lists

maxconts <- which(cards == max(cards))[1] #Select the first region
NW.dataset$NAME[maxconts]
```

```{r}
fg <- rep("grey", length(cards))
fg[maxconts] <- "red"
fg[xxnb[[maxconts]]] <- "green"
plot(NW.dataset, col=fg)
text(coordinates(NW.dataset), label=NW.dataset$NAME,cex=0.5)
title(main="Region with largest number of contiguities")
```


# After establishing the neighbours we look for the weigths

standardised weigths
```{r}
w.sids<-nb2listw(xxnb, glist=NULL, style="W", zero.policy=TRUE) #Spatial weights for neighbours li# w.sids$weights
summary(unlist(w.sids$weights))

head(w.sids$weights)
```

# TEST for autocorrelation ( o spatial correlation ??)
```{r}
sids.moran<-moran.test(NW.dataset$SMR ,w.sids) #Standardazed weights
sids.moran
```

```{r}
set.seed(1234)
sids.moran.mc<-moran.mc(NW.dataset$SMR, listw=w.sids, nsim=5000)
sids.moran.mc
```










